# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Pipe

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'datasets/**'
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'datasets/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the layers code with pylint
      run: |
        pylint layers --rcfile=.github/pylint.conf
    - name: Analysing the models code with pylint
      run: |
        pylint models --rcfile=.github/pylint.conf